

services:
  db:
    image: mysql:8.0
    container_name: cppt_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cppt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  web:
    build: .
    container_name: cppt_web
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: cppt_db
    depends_on:
      - db
    restart: always

volumes:
  db_data:
